name: Deployment to server
on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: self-hosted
    steps:
      - uses: rjstone/discord-webhook-notify@v1
        with:
          severity: info
          details: Deployment started...
          webhookUrl: ${{ secrets.DISCORD_WEBHOOK }}
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - run: |
          cd ..
          rm -rf umaestro_front_new
          cp -r umaestro_front umaestro_front_new
          cd umaestro_front_new
          git checkout main
          git reset --hard origin/main
          git pull
          npm rebuild
          npm install

          # Build the api

          npm run build

          # Replace current version with the new one

          cd ../
          mv umaestro_front umaestro_front_old
          mv umaestro_front_new umaestro_front

          # Restart server

          cd umaestro_front
          pm2 delete umaestro_front
          pm2 start .output/server/index.mjs --name umaestro_front
          rm -rf ../umaestro_front_old
      - uses: rjstone/discord-webhook-notify@v1
        if: success()
        with:
          severity: info
          details: Nouvelle version déployée avec succès
          webhookUrl: ${{ secrets.DISCORD_WEBHOOK }}
      - uses: rjstone/discord-webhook-notify@v1
        if: failure()
        with:
          severity: error
          details: Something went wrong...
          webhookUrl: ${{ secrets.DISCORD_WEBHOOK }}
      - uses: rjstone/discord-webhook-notify@v1
        if: cancelled()
        with:
          severity: warn
          details: Deploy cancelled...
          webhookUrl: ${{ secrets.DISCORD_WEBHOOK }}
